name: deploy react to github page
on:
    pull_request:
        branches:
            - main
        types: [closed]
jobs:
    build:
        if: github.event.pull_request.merged == true
        name: Build and deploy gh-pages
        env:
            MY_SECRET: ${{secrets.commit_secret}}
            USER_NAME: githubaction
            USER_EMAIL: githubaction@fake.com
            PUBLISH_DIR: ./build
            REPO_NAME: ${{ github.event.repository.name }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
            - name: install
              run: |
                  yarn
            - name: build
              run: |
                  yarn build -- --base-href "/$REPO_NAME/"
            - name: Commit files
              run: |
                  cd $PUBLISH_DIR
                  touch .nojekyll
                  git init
                  git config --local user.name $USER_NAME
                  git config --local user.email $USER_EMAIL
                  git status
                  git remote add origin https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git
                  git checkout -b gh-pages
                  git add --all
                  git commit -m "deploy to Github pages"
                  git push origin gh-pages -f
                  echo 🤘 deploy gh-pages complete.
